const header = () => {
  return {
    handle: "Handle",
    title: "title",
    body: "Body (HTML)",
    vendor: "Vendor",
    type: "Type",
    tags: "Tags",
    published: "Published",
    option1_name: "Option1 Name",
    option1_value: "Option2 Value",
    option2_name: "Option2 Name",
    option2_value: "Option2 Value",
    option3_name: "Option3 Name",
    option3_value: "Option3 Value",
    variant_sku: "Variant SKU",
    variant_grams: "Variant Grams",
    variant_inventory: "Variant Inventory Tracker",
    variant_inventory_qty: "Variant Inventory Qty",
    variant_inventory_policy: "Variant Inventory Policy",
    variant_fulfillment_service: "Variant Fulfillment Service",
    variant_price: "Variant Price",
    variant_compate_at_price: "Variant Compare At Price",
    variant_requires_shipping: "Variant Requires Shipping",
    variant_taxable: "Variant Taxable",
    variant_barcode: "Variant Barcode",
    image_src: "Image Src",
    image_position: "Image Position",
    image_alt_text: "Image Alt Text",
    gift_card: "Gift Card",
    seo_title: "SEO Title",
    seo_description: "SEO Description",
    google_shopping_product_category:
      "Google Shopping / Google Product Category",
    google_shopping_gender: "Google Shopping / Gender",
    google_shopping_age_group: "Google Shopping / Age Group",
    google_shopping_mpn: "Google Shopping / MPN",
    google_shopping_adwords_grouping: "Google Shopping / AdWords Grouping",
    google_shopping_adwords_label: "Google Shopping / AdWords Labels",
    google_shopping_condition: "Google Shopping / Condition",
    google_shopping_custom_products: "Google Shopping / Custom Product",
    variant_image: "Variant Image",
    variant_weight_unit: "Variant Weight Unit",
    variant_tax_code: "Variant Tax Code",
    cost_per_item: "Cost per item",
    status: "Status"
  };
};

exports.header = header;
